### ISSUE TITLE
Replace Ignition Provider

### ISSUE THREAD

**Issue by TheRealDwright** [BitGo/terraform-aws-bastion#33]
Currently, when using this module on an M1 (ARM) Mac, users will receive the error:

```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/terraform-providers/ignition v1.2.1 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
╵
```

Use of the ignition provider will need to be replaced to something with broader hardware support, it seems that the repository has been [archived](https://github.com/hashicorp/terraform-provider-ignition) on GitHub.

**Comment by james-callahan** [comment]
There's a demo repo over here: https://github.com/flatcar-linux/flatcar-terraform/tree/main/aws

Looks like they just template the userdata

**Comment by TheRealDwright** [comment]
Completed by #34
